#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: openjdk:15

pipelines:
  default:
    - step:
        script:
          - echo "Nothing to do here"
  branches:
    master:
      - step:
          name: Build
          caches:
            - gradle
          script:
            - bash ./gradlew packageMsi
          artifacts:
            - /build/compose/binaries/main/msi/**
      - step:
          name: Test jfrog connection
          script:
            - pipe: jfrog/jfrog-setup-cli:1.0.0
            - source ./jfrog-setup-cli.sh
            - jfrog rt ping --url https://voicehera.jfrog.io/artifactory/
      - step:
          name: Deploy to production
          deployment: production
          script:
            - pipe: jfrog/jfrog-setup-cli:1.0.0
            - source ./jfrog-setup-cli.sh
            - jfrog rt u file artifacts/