#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: openjdk:15

pipelines:
  default:
    - step:
        script:
          - echo "Nothing to do here"
  branches:
    master:
      - step:
          name: Build
          caches:
            - gradle
          script:
            - bash ./gradlew packageMsi
            - bash ls
          artifacts:
            - build/compose/**
            - build/**
            - builds/**
      - step:
          name: Upload to downloads section
          deployment: staging
          script:
            - pipe: atlassian/bitbucket-upload-file:0.3.1
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: '**/voice*.msi'
      - step:
          name: Test jfrog connection
          script:
            - pipe: jfrog/jfrog-setup-cli:1.0.0
            - source ./jfrog-setup-cli.sh
            - jfrog rt ping --url https://voicehera.jfrog.io/artifactory/
      - step:
          name: Deploy to production
          deployment: production
          script:
            - pipe: jfrog/jfrog-setup-cli:1.0.0
            - source ./jfrog-setup-cli.sh
            - jfrog rt u **/*.msi file --url https://voicehera.jfrog.io