# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    tags:
      - "v*"
    branches: [ master ]
    
jobs:
  build:

    runs-on: windows-latest
    env:
      SPEECH_API_KEY: "${{ secrets.GITHUB_TOKEN }}"
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '16'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.1
    - run: gradle packageMsi
    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: build/compose/binaries/main/msi/*.msi
    - name: Setup latest release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Latest"
        prerelease: false
        files: |
          build/compose/binaries/main/msi/*.msi